[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Poli Náutico"
authors = [{name = "Equipe Poli Náutico", email = "nautico.poli@gmail.com"}]
dynamic = ["version", "description"]
